### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by anwoke8204** [d3vilh/raspberry-gateway#37]
hi, I am having to use the cli install and once it starts to install any of the addons like portainer or any of the dns or other options I get 

Fatal:  [raspberry_gateway] FAILED! => {"changed"; false, "msg": "error connectiong: error while fetching servrer API version: {Connection aborted.",  PermissionError{13, 'permissiondenied'}}"}

any idea how I can resolve this issue?

**Comment by d3vilh** [comment]
HI @anwoke8204, 
Try to login/logout. Most probably you had no docker or ansible installed and those errors are about your current session is lacking permissions.

Let me know if that helps.

**Comment by anwoke8204** [comment]
It looks like that worked. How do I set a static ip on the gateway
________________________________

**Comment by d3vilh** [comment]
> It looks like that worked. How do I set a static ip on the gateway

IP is something your DHCP server assign (Probably WiFi router), so you need to make it static there and it will be static forever.

**Comment by anwoke8204** [comment]
This will be my dhcp server as well as my gateway/router/firewall for my network hence why it needs a set static ip address on the device itself.
________________________________

**Comment by anwoke8204** [comment]
is there a way to configure the dhcp server via cli during initial config and setup?  also when I run ip addr I get a bunch of virtual network cards, how can I get it to just show the ip address on the local ethernet and the usb ethernet card so I can make sure they are correct?
3

**Comment by anwoke8204** [comment]
I foobarred tryhing to set up a static ip so I had to reinstall and now I am back to getting
Fatal: [raspberry_gateway] FAILED! => {"changed"; false, "msg": "error connectiong: error while fetching servrer API version: {Connection aborted.", PermissionError{13, 'permissiondenied'}}"}

I have made sure that docker compose and ansible are installed and have rebooted several times incase it was a permissions issue..  the only difference I did this time was I preconfigured the username and location by clicking on the gear using the raspberry imager before i wrote the os to the card this time.

**Comment by d3vilh** [comment]
I glad you figure out how to set permanent IP.

> I have made sure that docker compose and ansible are installed an

If you have different than `pi` username, than you do need to update it in [`inventory.yml`](https://github.com/d3vilh/raspberry-gateway/blob/f79f66fb7b9cb711c8cbd5b1092d2ecf07478939/example.inventory.yml#L6) prior running installation. It is point 6 of [manual installation procedure](https://github.com/d3vilh/raspberry-gateway/tree/master?tab=readme-ov-file#installation).

It is again user permissions mismatch :)
Before getting with reinstallation, try to update `inventory.yml` and run it with new user. It should work fine.

**Comment by d3vilh** [comment]
congrats. You could run `webinstall` binary, it will show you local raspberry IP address and port to connect too.
```bash
:~/raspberry-gateway $ ./webinstall
2024/02/21 09:32:40 Welcome! The web interface will guide you on installation process.
Installation logs: webinstall.log
2024/02/21 09:32:40 Starting web server on http://192.168.88.9:8088
```

Once you connect on this IP:PORT, you could scroll down for quick links to the services and its ports:

![Знімок екрана 2024-02-21 о 09 35 29](https://github.com/d3vilh/raspberry-gateway/assets/33333559/b04f372d-c857-415f-a49c-789b36c86282)

We also have quick info for all the services under [Usage](https://github.com/d3vilh/raspberry-gateway?tab=readme-ov-file#usage) section of the Readme.md file.

**Comment by anwoke8204** [comment]
For  some reason I am not able to get to the website listed when I run that?  Is there a way you could send me a list of all the ports for everything?  I am able to get into portainer, is there a way I can launch the web interface for each of the other interfaces for the other features I had installed?  If so, how do I do it?  Sorry I am new to portainer and docker.
________________________________

**Comment by d3vilh** [comment]
When you run services in Docker containers, each service can expose ports to the host system. 
These ports allow you to interact with the service from outside the Docker container, such as accessing a web interface via your browser.

Open a terminal and run:

```bash 
docker ps
```

This command lists all running containers. Look for the "PORTS" column in the output. It shows which ports are exposed and mapped to the host. For example, you might see something like `0.0.0.0:8080->80/tcp`, indicating that the container's port 80 is accessible at port 8080 on your host machine.

To access the web interface of a service running inside a container, you need to know which port it is exposed on your host machine. Once you have this information (e.g., port 8080 for a specific service), you can access it using your web browser by navigating to:

```php
http://<your-host-ip>:<port>/
```
Replace <your-host-ip> with the IP address of your host machine and <port> with the port number you found under [Usage section ](https://github.com/d3vilh/raspberry-gateway?tab=readme-ov-file#usage)of Readme.md.

Since you mentioned you're able to access Portainer, you can also use it to find port information and manage your containers more visually, which might be easier if you're new to Docker.
In Portainer, navigate to the "Containers" section to see a list of your containers. Click on a container to see its details, including its port mappings.

How I mentioned earlier, you could have luck links to most important services in webinstall webpage (share `webinstall` output and I'll help you with the IP)

**Comment by d3vilh** [comment]
Hey @anwoke8204 
how are you doing? Do you managed to bring it up finally?

**Comment by anwoke8204** [comment]
Unfortunately no
________________________________

**Comment by d3vilh** [comment]
If you still have desire, I recommend to try `webinstall`.

It rocks for people who don't like dig details and would avoid problems.
